# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djciv_data', '0014_collection_collcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collcat',
            field=models.TextField(),
        ),
    ]
